import DetailsPage from "./nftList";


export const metadata = {
  title: 'Details NFT',
  description: 'Generated by create next app',
};
 
const Home = () => {
  return (
    <div>
      <h2 className="text-2xl mb-5">More detail on favorite Ntfs</h2>
      <DetailsPage />
    </div>
  )
}

export default Home