import Footer from '@/src/components/Footer';
import Navigation from '@/src/components/Navigation';
import ToastContainerFunction from '@/src/utils/toast';
import './globals.css';
import { AppProviders } from './providers';
import { UserContextProvider } from '@/src/context/user';



export const metadata = {
  title: 'NFT marketplace',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <AppProviders>
        <UserContextProvider>
          <body className="text-white bg-gray-900 min-h-full flex flex-col container mx-auto sm:p-0 p-4">
            <Navigation />
            {children}
            <Footer />
            <ToastContainerFunction />
          </body>
        </UserContextProvider>
      </AppProviders>
    </html>
  );
}

/* 

body{
    min-height: 100vh;
    display: flex;
    flex-direction: column;
}
article {
    margin: auto 0;
}

*/


/* type Props = {
  params: { id: string };
  searchParams: { [key: string]: string | string[] | undefined };
};

export async function generateMetadata({ params, searchParams }: Props) {
  return {
    title: '...',
  };
} */
